# Android

# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
- group: release

steps:

- task: Gradle@2

  inputs:

    workingDirectory: ''

    gradleWrapperFile: 'gradlew'

    gradleOptions: '-Xmx3072m'

    javaHomeOption: 'JDKVersion'

    jdkVersionOption: '1.8'

    jdkArchitectureOption: 'x64'

    publishJUnitResults: false

    testResultsFiles: '**/TEST-*.xml'

    tasks: 'assembleDebug'

- task: AndroidSigning@3

  inputs:

    apkFiles: '**/*.apk' 

    apksign: true

    apksignerKeystoreFile: production.jks

    apksignerKeystorePassword: $(keystore.password)

    apksignerKeystoreAlias: $(key.alias)

    apksignerKeyPassword: $(key.password)

    apksignerArguments: --out $(Build.SourcesDirectory)/android-devops.apk

    zipalign: false

- task: CopyFiles@2

  inputs:

    SourceFolder: $(Build.SourcesDirectory)

    contents: '**/*.apk'

    targetFolder: '$(build.artifactStagingDirectory)'

    overWrite: true


- script: |

    cd functions

    npm init --yes

    npm install -g firebase-tools

    npm install

    firebase appdistribution:distribute --app $(Firebase.APP_ID) --token $(Firebase.FIREBASE_TOKEN) --release-notes $[variables.notes] --testers "infantjoseph@gmail.com" $(build.artifactStagingDirectory)/android-devops.apk
      
  displayName: 'Firebase install and deploy'
